# An example .director.yml file, would work for a symfony app.

# List of services this app requires.
# name: type.
services:
    web: apache
    database: mysql

web:
    document_root: "/www"

hooks:
    build: |
      drush make drupal.make www -y
    deploy: |
      drush status
      drush updb -y
      drush cc all
