# An example .director.yml file, would work for a symfony app.

# List of services this app requires.
# name: type.
services:
    web: apache
    database: mysql

web:
    document_root: "/www"

hooks:
    build: |
      drush make drupal.make www --prepare-install -y
    deploy: |
      drush updb -y
      drush cc all
